language: java

os: linux
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7
  - openjdk8

jobs:
  include:
    - jdk: openjdk11
      before_install:
        - echo "security.provider.13=org.bouncycastle.jce.provider.BouncyCastleProvider" >> "${JAVA_HOME}/conf/security/java.security"

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - dennis.detering@rub.de
