language: java

sudo: false

dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7
  - openjdk8

branches:
  only:
    - master
    - /^test\/.*$/

notifications:
  email:
    recipients:
      - dennis.detering@rub.de
