language: java

os: linux
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

branches:
  only:
    - master
    - /^test\/.*$/

notifications:
  email:
    recipients:
      - dennis.detering@rub.de
